Areas/AreaPersonaTriaje/Controllers/PersonaTriajeController.cs
using BLCovid;
using DACovid;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TRIAJE_COVID.Areas.AreaPersonaTriaje.Controllers
{
    public class PersonaTriajeController : Controller
    {
        // GET: AreaPersonaTriaje/PersonaTriaje
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Listado()
        {
            ViewBag.ListadoPersona = PersonaBL.Listado();
            return PartialView();
        }

        [HttpPost]
        public JsonResult Grabar(string nombrePersona,string apellidos,int edad, string sexo, string ocupacion, string sintomas, string direccion )
        {
            PersonaTriaje persona = new PersonaTriaje
            {
                Nombres = nombrePersona,
                Apellidos = apellidos,
                Edad = edad,
                Sexo = sexo,
                Ocupacion = ocupacion,
                Sintomas = sintomas,
                Direccion = direccion
            };
            bool exito = true;
            PersonaBL.Registrar(persona);           

            return Json(exito, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Eliminar(int codigoPersona)
        {
            bool exito = PersonaBL.Eliminar(codigoPersona);
            return Json(exito, JsonRequestBehavior.AllowGet);
        }

    }
}

Areas/Main/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COVIDProyecto2._0.Areas.Main.Controllers
{
    public class MainController : Controller
    {
        // GET: Main/Main
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Menu()
        {
            return View();
        }
    }
}

Areas/PersonalAdmin/Controllers/PersonalAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using COVIDProyecto2._0.Models;
using System.Web.Security;
using System.Runtime.Remoting.Messaging;
using BLCovid;
using DACovid;

namespace COVIDProyecto2._0.Areas.PersonalAdmin.Controllers
{
    public class PersonalAdminController : Controller
    {
        // GET: PersonalAdmin/PersonalAdmin

        public ActionResult Reporte()
        {
            return View();
        }
        public ActionResult Login()
        {
            if (Session["UserAdmin_id"] != null)
            {
                return RedirectToAction("Menu");
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public JsonResult LogearUsuario(string user, string pass)
        {
            // BOPersonalAdmin personal = DAPersonalAdmin.GetUser(user, pass);
            PersonalAdministrativo personal = LoginBL.GetUser(user, pass);
            bool exito;
            if (personal != null)
            {
                Session["UserAdmin_nombre"] = personal.Nombres + " " + personal.Apellidos;
                Session["UserAdmin_id"] = personal.ID;
                exito = true;
            }
            else
            {
                exito = false;
            }
            return Json(exito);

        }
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        public ActionResult Menu()
        {
            if (Session["UserAdmin_id"] != null)
            {
                return View();
            }
            else
            {
               return RedirectToAction("Login");
            }
            
        }
    }
}

Areas/Main/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="navbar" class="header">
    <h2 class="logo">#YoApoyoPerú</h2>
    <input type="checkbox" id="chk">
    <label for="chk" class="show-menu-btn">
        <ion-icon class="ion" name="menu"></ion-icon>
    </label>

    <ul class="menu">
        <a href="#ayudar">Como ayudar</a>
        <a href="#W2help">Contactanos</a>
        <a href="#conocenos">Conocenos</a>
        <a href="@Url.Action("Login","PersonalAdmin",new { Area = "PersonalAdmin" })">Personal Administrativo</a>

        <label for="chk" class="hide-menu-btn">
            <ion-icon class="ion" name="close-outline"></ion-icon>
        </label>
    </ul>
</div>

<div class="banner-area">
    <!-- revisar container prox ves -->
    <div class="banner-text">
        <h1 class="title-text">#YoApoyoPerú</h1>
        <p class="menu-btn" onclick="location.href='@Url.Action("Menu","Main",new { Area = "Main" })';">Ir al menu</p>
    </div>
</div>

<div class="page-section" id="ayudar">
    <div class="text-center">
        <h2 class="subtitle-text">¿Como apoyar?</h2>
        <p style="text-align: justify;" class="paragraph-text">
            #APOYAALOSQUELONECESITAN, Una iniciativa impulsada por los alumnos de Desarrollo Web de la Universidad Esan  con el objetivo de promover el apoyo a familias vulnerables llamando  a la generosidad mediante las donaciones y unidad como respuesta de emergencia social y sanitaria causada por el COVID-19
        </p>
    </div>

</div>

<div class="page-section" id="W2help">
    <div class="text-center">
        <h2 class="subtitle-text">Súmate A #QuedateEnCasa</h2>
        <p class="main-text">Comparte tu acto de generosidad con #YoApoyoPeru</>
    </div>
</div>

<section class="page-section" id="conocenos">
    <div class="container-fluid">
        <div class="text-center">
            <h2 class="subtitle-text">¿Que es #YoApoyoPeru?</h2>
            <p class="main-text">#YoApoyoPeru es un movimiento estudiantil impulsado por cinco universitarios que quiere incentivar y multiplicar las buenas acciones de las personas.</p>
        </div>

    </div>

</section>

<section id="texto2info" class="page-section">
    <div class="container ">
        <div class="text-center">
            <a class="twitter-timeline" data-lang="es" data-width="1000" data-height="700" data-theme="white" href="https://twitter.com/larepublica_pe">h</a>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

        </div>
    </div>
</section>


<section id="texto2info" class="page-section">
    <div class="container ">
        <div class="text-center">
            <a class="twitter-timeline" data-lang="es" data-width="1000" data-height="700" data-theme="white" href="https://twitter.com/elcomercio_peru"></a>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

        </div>
    </div>
</section>



<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
<script type="text/javascript">
    window.addEventListener("scroll", function () {
        let menuArea = document.getElementById('navbar');

        if (window.pageYOffset > 40) {
            menuArea.classList.add("cus-nav");
        } else {
            menuArea.classList.remove("cus-nav");
        }
    })
</script>

Areas/Main/Views/Main/Menu.cshtml
@{
    ViewBag.Title = "Menu";
    Layout = "~/Areas/Main/Views/Shared/_Menulayout.cshtml";
}
<link href="~/Estilos/Style4.css" rel="stylesheet" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<ul class="ul-menu" style="color: black;">
    <li onclick="location.href='@Url.Action("Reporte","PersonalAdmin",new { Area = "PersonalAdmin" })';">
        <span class="name">Registro Situacional</span>
        <span><i class="fa fa-bar-chart" aria-hidden="true"></i></span>
    </li>
    <li onclick="location.href='@Url.Action("Index","PersonaTriaje",new { Area = "AreaPersonaTriaje" })';">
        <span class="name">Triaje Digital</span>
        <span><i class="fa fa-hospital-o" aria-hidden="true"></i></span>
    </li>
    <li>
        <span class="name">Registro de personas en extrema pobreza</span>
        <span><i class="fa fa-book" aria-hidden="true"></i></span>
    </li>
    <li>
        <span class="name">Registro de donaciones</span>
        <span><i class="fa fa-cart-plus" aria-hidden="true"></i></span>
    </li>
</ul>