Areas/Administrador/Controllers/RDonacionesController.cs
using BLCovid;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recepción_Donaciones.Areas.Administrador.Controllers
{
    public class RDonacionesController : Controller
    {
        // GET: Administrador/RDonaciones
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Listado()
        {
            ViewBag.ListadoDonacion = DonacionesDL.Listado();
            return PartialView();
        }
    }
}

Areas/Administrador/Controllers/RecepcionController.cs
using BLCovid;
using DACovid;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recepción_Donaciones.Areas.Administrador.Controllers
{
    public class RecepcionController : Controller
    {
        // GET: Administrador/Recepcion
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Listado()
        {
            ViewBag.ListadoDonacion = DonacionesDL.Listado();
            return PartialView();
        }
    }
}

Areas/AreaPersonaTriaje/Controllers/PersonaTriajeController.cs
using BLCovid;
using DACovid;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TRIAJE_COVID.Areas.AreaPersonaTriaje.Controllers
{
    public class PersonaTriajeController : Controller
    {
        // GET: AreaPersonaTriaje/PersonaTriaje
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Listado()
        {
            ViewBag.ListadoPersona = PersonaBL.Listado();
            return PartialView();
        }

        [HttpPost]
        public JsonResult Grabar(string nombrePersona,string apellidos,int edad, string sexo, string ocupacion, string sintomas, string direccion )
        {
            PersonaTriaje persona = new PersonaTriaje
            {
                Nombres = nombrePersona,
                Apellidos = apellidos,
                Edad = edad,
                Sexo = sexo,
                Ocupacion = ocupacion,
                Sintomas = sintomas,
                Direccion = direccion
            };
            bool exito = true;
            PersonaBL.Registrar(persona);           

            return Json(exito, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Eliminar(int codigoPersona)
        {
            bool exito = PersonaBL.Eliminar(codigoPersona);
            return Json(exito, JsonRequestBehavior.AllowGet);
        }

    }
}

Areas/PersonalAdmin/Controllers/PersonalAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using COVIDProyecto2._0.Models;
using System.Web.Security;
using System.Runtime.Remoting.Messaging;
using BLCovid;
using DACovid;

namespace COVIDProyecto2._0.Areas.PersonalAdmin.Controllers
{
    public class PersonalAdminController : Controller
    {
        // GET: PersonalAdmin/PersonalAdmin

        public ActionResult Reporte()
        {
            return View();
        }
        public ActionResult Login()
        {
            if (Session["UserAdmin_id"] != null)
            {
                return RedirectToAction("Menu");
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public JsonResult LogearUsuario(string user, string pass)
        {
            // BOPersonalAdmin personal = DAPersonalAdmin.GetUser(user, pass);
            PersonalAdministrativo personal = LoginBL.GetUser(user, pass);
            bool exito;
            if (personal != null)
            {
                Session["UserAdmin_nombre"] = personal.Nombres + " " + personal.Apellidos;
                Session["UserAdmin_id"] = personal.ID;
                exito = true;
            }
            else
            {
                exito = false;
            }
            return Json(exito);

        }
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        public ActionResult Menu()
        {
            if (Session["UserAdmin_id"] != null)
            {
                return View();
            }
            else
            {
               return RedirectToAction("Login");
            }
            
        }
    }
}

Areas/PersonalAdmin/Views/PersonalAdmin/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Areas/PersonalAdmin/Views/Shared/_Adminlayout.cshtml";
}

<body id="bodyLogin">
    <section id="loginAdmin">
        <div class="login-box">
            <ion-icon name="person-circle-outline" class="avatar"></ion-icon>
            <h1>Personal Administrativo</h1>
            <form id="formLogin">
            @*<form id="formLogin" method="post" action="@Url.Action("Login","PersonalAdmin",new { Area = "PersonalAdmin" })">*@ 
                <label for="username">Usuario</label>
                <input type="text" name="txtUsuario" id="txtUsuario" placeholder="Ingresar usuario">
                <label for="password">Contraseña</label>
                <input type="password" name="txtPass" autocomplete="on" id="txtPass" placeholder="Ingresar contraseña">
                <input type="submit" id="btnLogin" value="Ingresar">

            </form>
        </div>
       
    </section>

</body>

<script>
    $("#btnLogin").click(function () {
        var vUser = $("#txtUsuario").val();
        var vPassword = $("#txtPass").val();
        
        if (vUser == "" || vPassword == "") {
            alert("Rellenar todos los campos");
            return false;
        }
        $.ajax({
            type: "POST",
            url: "/PersonalAdmin/PersonalAdmin/LogearUsuario",
            data: { user: vUser, pass: vPassword },
            success: function (data) {
                if (data==true) {
                    alert("Usuario y contraseña correctos");
                    window.location.href = '@Url.Action("Menu","PersonalAdmin",new { Area = "PersonalAdmin" })'
                } else {
                    alert("Usuario y/o contraseña incorrecto");
                }
            }
        });
    });

</script>

Areas/PersonalAdmin/Views/PersonalAdmin/Menu.cshtml
@{
    ViewBag.Title = "Menu";
    Layout = "~/Areas/PersonalAdmin/Views/Shared/_Menulayout.cshtml";
}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Estilos/Style4.css" rel="stylesheet" />

<ul class="ul-menu" style="color: black;">
    <li onclick="location.href='@Url.Action("Reporte","PersonalAdmin",new { Area = "PersonalAdmin" })';">
        <span class="name">Registro Situacional</span>
        <span><i class="fa fa-bar-chart" aria-hidden="true"></i></span>
    </li>
    <li onclick="location.href='@Url.Action("Index","PersonaTriaje",new { Area = "AreaPersonaTriaje" })';">
        <span class="name">Triaje Digital</span>
        <span><i class="fa fa-hospital-o" aria-hidden="true"></i></span>
    </li>
    <li>
        <span class="name">Registro de personas en extrema pobreza</span>
        <span><i class="fa fa-book" aria-hidden="true"></i></span>
    </li>
    <li>
        <span class="name">Registro de donaciones</span>
        <span><i class="fa fa-cart-plus" aria-hidden="true"></i></span>
    </li>
    <li>
        <span class="name">Confirmación de recepción de donaciones</span>
        <span><i class="fa fa-archive" aria-hidden="true"></i></span>
    </li>
    <li>
        <span class="name">Entrega de donaciones</span>
        <span><i class="fa fa-car" aria-hidden="true"></i></span>
    </li>
    <li>
        <span class="name">Reporte de Triajes</span>
        <span><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
    </li>
    <li onclick="location.href='@Url.Action("Index", "Recepcion", new { Area = "Administrador" })';">
        <span class="name">Recepción de donaciones</span>
        <span><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
    </li>
    <li onclick="location.href='@Url.Action("Index","RDonaciones",new { Area = "Administrador" })';">
        <span class="name">Reporte de donaciones</span>
        <span><i class="fa fa-file-text" aria-hidden="true"></i></span>
    </li>

</ul>

Areas/PersonalAdmin/Views/PersonalAdmin/Reporte.cshtml
@{
    ViewBag.Title = "Reporte";
    Layout = "~/Areas/PersonalAdmin/Views/Shared/_ReporteLayout.cshtml";
}


<script>



    CargarNumeros();

    function CargarNumeros() {
        $.ajax({
            url: "https://corona.lmao.ninja/v2/countries/Peru?yesterday=true&strict&query",
            success: function (result) {
                $('#tot1').html(result.cases);
                $('#tot2').html(result.recovered);
                $('#tot3').html(result.deaths);
                $('#tot4').html(result.active);
                $('#dia1').html(result.todayCases);
                $('#dia2').html(result.todayRecovered);
                $('#dia3').html(result.todayDeaths);
                $('#dia4').html(result.critical);
            }
        });
        $.ajax({
            url: "https://corona.lmao.ninja/v2/historical/Peru?lastdays=30",
            success: function (result) {
                console.log(result.timeline.cases);                
                var cases = []; var recu = [];var death = [];

                for (var i in result.timeline.cases) {
                    cases.push(result.timeline.cases[i]);
                }
                for (var i in result.timeline.recovered) {
                    recu.push(result.timeline.recovered[i]);
                }
                for (var i in result.timeline.deaths) {
                    death.push(result.timeline.deaths[i]);
                }
                x=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];
                console.log(cases);     
                if ($('#grafico1').length) {
                    $("#grafico1").sparkline(cases, {
                        type: 'line',
                        lineColor: '#ff0451',
                        fillColor: '#dffaff',
                        width: '100%',
                        height: '100',
                        spotColor: '#ff407b',
                        minSpotColor: '#ff407b',
                        maxSpotColor: '#ff407b',
                        
                        lineWidth: '2',
                        barColor: '#5969ff'
                    });
                }
                if ($('#grafico2').length) {
                    $("#grafico2").sparkline(recu, {
                        type: 'line',
                        width: '100%',
                        height: '100',
                        spotColor: '#ff407b',
                        minSpotColor: '#ff407b',
                        maxSpotColor: '#ff407b',
                        lineColor: '#AF7E1D',
                        fillColor: '#FFAA00',
                        lineWidth: '2'
                    });
                }
                if ($('#grafico3').length) {
                    $("#grafico3").sparkline(death, {
                        type: 'line',
                        width: '100%',
                        height: '100',
                        spotColor: '#ff407b',
                        minSpotColor: '#ff407b',
                        maxSpotColor: '#ff407b',
                        lineColor: '#8C1212',
                        fillColor: '#F53E3E',
                        lineWidth: '2'
                    });
                }
                Morris.Area({
                    element: 'morris_totalrevenue1',
                    behaveLikeLine: true,
                    data: [x,x],
                    xkey: 'x',
                    ykeys: ['y'],
                    labels: ['Y'],
                    lineColors: ['#5969ff'],
                    resize: true

                });
            }
        });
    }
</script>